#!/bin/bash

#This script assumes that:
# java has already been added to the path and that it is accessible and has sufficient permissions to run OpenTripPlanner.
# the GTFS file put into newGtfsDataDir will always have the same name.
# otp has been started and is watching a specific directory for new graphs to be put in

############################################################
## Default Setup Instructions
############################################################

# 1 - Create the following directories and make sure that permissions allow for writing
# /var/otp/bin
# /var/otp/data
# /var/otp/graphs/<your graph folder name>
# /var/otp/gtfs_current
# /var/otp/gtfs_new
# /var/otp/osm_current
# /var/otp/osm_new

# 2 - Put your Jar File in /var/otp/bin

# 3 - Put your gtfs excel file in /var/otp/bin
# There should be two columns (Name,URL) Note: only URL is used, the name simply for reference

# 4 - Put your OSM excel file in /var/otp/bin
# There should be two columns (Name,URL) Note: only URL is used, the name simply for reference

# 5 - Update the directories in the Customizable stuff you probably want to change below

############################################################
## The Customizable Section
############################################################

######## Stuff you probably want to change
#This should be a CSV with the following format: NAME of Service, URL of GTFS
gtfsExcelFile=/var/otp/bin/gtfs_locations.csv
#This should be a CSV with the followig format: NAME of the OSM, URL of OSM
osmExcelFile=/var/otp/bin/osm_locations.csv
#This should be set to the directory where OTP is expecting graphs to be placed
otpGraphDir=/var/otp/graphs/ma/
#Specific OTP version
otpJar=otp-1.0.0-shaded.jar
#Email Distribution List (comma separated)
emailDistributionList=dedwards8@gmail.com

######## Stuff you probably DON'T want to change
#This should be set to the the local directory where new GTFS data is stored
newGtfsDataDir=/var/otp/gtfs_new/
#This should be set to the local directory where the Currently used GTFS data is stored
currentGtfsDataDir=/var/otp/gtfs_current/
#New Osm Directory
newOsmDataDir=/var/otp/osm_new/
#Current Osm Directory
currentOsmDataDir=/var/otp/osm_current/
#This is the folder that combines the GTFS and OSM.  The graph is built from this folder
buildDataDir=/var/otp/data/
#This should be the filename of the graph object. This is always Graph.obj when OTP builds it.
graphFileName=Graph.obj
#This should be the directory of the OpenTripPlanner jar that is serving the instance of OTP on this server
otpJarDirectory=/var/otp/bin/
#This should be the parameters used when invoking the OpenTripPlanner test new GTFS data
invokeJavaCommand="java -Xmx4G -jar"

############################################################
## Pre Clean-Up
############################################################
clear
echo "Starting at";  date
echo "Cleaning Up"

#Delete everything in the New GTFS Folder
rm -rf $newGtfsDataDir*

#Delete everything in the new OSM Folder
rm -rf $newOsmDataDir*

#Get rid of the old gtfs temp file if it exists
tempFile=$otpJarDirectory"temp.csv"
if [ -f $tempFile ] ; then
    rm $tempFile
fi

#Get rid of the old OSM temp file if it exists
osmTempFile=$otpJarDirectory"osm_temp.csv"
if [ -f $osmTempFile ] ; then
    rm $osmTempFile
fi

############################################################
## Download GTFS
############################################################
echo "Reading CSV of GTFS locations"
while IFS="," read Name URL
do
  echo $URL >> $tempFile
done < $gtfsExcelFile
wget -i $tempFile -P $newGtfsDataDir

#TODO: Check to see any of the GTFS files failed to download

#Check to see  if the new GTFS is different than the current GTFS
diffResult=$(diff $newGtfsDataDir $currentGtfsDataDir)
if [ ! "$diffResult" ]; then #this is the mac stat. Redhat might want a different format
        echo "The GTFS has not been updated."
        exit 0
fi

#Delete everything in the build folder
rm -rf $buildDataDir*

echo "Copying new gtfs to current GTFS folder"
cp $newGtfsDataDir* $buildDataDir

############################################################
## Download OSM Map (only run if we have new GTFS)
############################################################
echo "Reading CSV of OSM locations"
##Go through the osmExcelFile and remove the names column.
while IFS="," read Name URL
do
    echo $URL >> $osmTempFile
done < $osmExcelFile
wget -i $osmTempFile -P $newOsmDataDir

#TODO: Check to see if the OSM was actually downloaded
#TODO EMAIL on Failure

############################################################
## Build the Graph
############################################################
$invokeJavaCommand $otpJarDirectory$otpJar "--build" $buildDataDir

############################################################
## Test the Graph
############################################################
# Get the graph size
graphSize=$(ls -l $buildDataDir$graphFileName | awk '{print $5}')
#If the graph is small, then it's not fully built.  This thing failed.
minSize=10
if [ $graphSize -lt $minSize ]; then
    echo "Fail"
    #TODO EMAIL
    exit 0
fi

############################################################
## SUCCESS! Clean-up, Upload Graph, and Restart OTP
############################################################
# Move the new GTFS to the current GTFS folder
rm -rf $currentGtfsDataDir*
cp $newGtfsDataDir* $currentGtfsDataDir

# Move the new OSM to the current OSM folder
rm -rf $currentOsmDataDir*
cp $newOsmDataDir* $currentOsmDataDir

# If there is Graph currently in production, move it to Graph.obj.old
if [ -f $otpGraphDir$graphFileName ] ; then
  cp $otpGraphDir$graphFileName $otpGraphDir$graphFileName.old
fi

#Move the new Graph to the production location
sudo cp $buildDataDir$graphFileName $otpGraphDir$graphFileName

#Check to see  if the new Graph was successfully moved
diffResult=$(diff $buildDataDir$graphFileName $otpGraphDir$graphFileName)
if [ "$diffResult" ]; then
  echo "The Graph.obj has not been moved into production."
  #TODO MAIL on Failure
  exit 0
fi

#TODO: Restart OTP
#TODO: Email Success






