#!/bin/bash

#This script assumes that:
# java has already been added to the path and that it is accessible and has sufficient permissions to run OpenTripPlanner.

############################################################
## Default Setup Instructions
############################################################

# 1 - Create the following directories and make sure that permissions allow for writing
# /var/otp/bin
# /var/otp/data
# /var/otp/graphs/<your graph folder name>
# /var/otp/gtfs_current
# /var/otp/gtfs_new
# /var/otp/osm_current
# /var/otp/osm_new

# 2 - Put your Jar File in /var/otp/bin

# 3 - Put your gtfs excel file in /var/otp/bin
# There should be two columns (Name,URL) Note: only URL is used, the name simply for reference

# 4 - Put your OSM excel file in /var/otp/bin
# There should be two columns (Name,URL) Note: only URL is used, the name simply for reference

# 5 - Update the directories in the Customizable stuff you probably want to change below

############################################################
## The Customizable Section
############################################################

######## Stuff you probably want to change
#This should be a CSV with the following format: NAME of Service, URL of GTFS
gtfsExcelFile=/var/otp/bin/gtfs_locations.csv
#This should be a CSV with the followig format: NAME of the OSM, URL of OSM
osmExcelFile=/var/otp/bin/osm_locations.csv
#This should be set to the directory where OTP is expecting graphs to be placed
otpGraphDir=/var/otp/graphs/ma/
#Specific OTP version
otpJar=otp-1.0.0-shaded.jar

######## Email Stuff
#Email Distribution List (comma separated)
emailDistributionList=dedwards8@gmail.com
#System Name or Identifier. Used when emailing
serverName="MA OTP Server"
#Are emails configured, and we want to send them
sendEmail=1
#Send emails even when nothing has changed. Even if no new GTFS has been pulled down, do you want an email letting you know that this script was run? (Everything is OK Alarm)
verboseEmail=1

######## Stuff you probably DON'T want to change
#This should be set to the the local directory where new GTFS data is stored
newGtfsDataDir=/var/otp/gtfs_new/
#This should be set to the local directory where the Currently used GTFS data is stored
currentGtfsDataDir=/var/otp/gtfs_current/
#New Osm Directory
newOsmDataDir=/var/otp/osm_new/
#Current Osm Directory
currentOsmDataDir=/var/otp/osm_current/
#This is the folder that combines the GTFS and OSM.  The graph is built from this folder
buildDataDir=/var/otp/data/
#This should be the filename of the graph object. This is always Graph.obj when OTP builds it.
graphFileName=Graph.obj
#This should be the directory of the OpenTripPlanner jar that is serving the instance of OTP on this server
otpJarDirectory=/var/otp/bin/
#This should be the parameters used when invoking the OpenTripPlanner test new GTFS data
invokeJavaCommand="java -Xmx4G -jar"

############################################################
## Pre Clean-Up
############################################################
clear
echo "Starting at";  date
echo "Cleaning Up"

#Delete everything in the New GTFS Folder
rm -rf $newGtfsDataDir*

#Delete everything in the new OSM Folder
rm -rf $newOsmDataDir*

#Get rid of the old gtfs temp file if it exists
tempFile=$otpJarDirectory"temp.csv"
if [ -f $tempFile ] ; then
    rm $tempFile
fi

#Get rid of the old OSM temp file if it exists
osmTempFile=$otpJarDirectory"osm_temp.csv"
if [ -f $osmTempFile ] ; then
    rm $osmTempFile
fi

############################################################
## Download GTFS
############################################################
echo "Reading CSV of GTFS locations"
while IFS="," read Name URL
do
  echo $URL >> $tempFile
done < $gtfsExcelFile
wget -i $tempFile -P $newGtfsDataDir

#Count the files in the directory to confirm all the GTFS downloaded
gtfsCount=$(ls $newGtfsDataDir | wc -l)
expectedGtfsCount=$(wc -l $gtfsExcelFile | awk '{print $1}')

# TEST 1: If expected number of GTFS files is different than what was downloaded.  Error!
if [ "$gtfsCount" -ne "$expectedGtfsCount" ] ; then
    echo "Error downloading some GTFS. The expected number of GTFS files differs from what was expected."
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some GTFS. The expected number of GTFS files differs from what was expected." | mail -s "$serverName Build Error" $emailDistributionList
    fi
    #TODO: Make this error more specific.  Which file didn't download?
    exit 0
fi

# TEST 2: If more than one file type was downloaded.  Error!
fileTypeCount=$(file $newGtfsDataDir* | awk '{print $2}' | sort | uniq | wc -l)
expectedFileTypeCount=1
echo "Downloaded the following number of GTFS file types (should always be 1)"
echo $fileTypeCount
if [ "$fileTypeCount" -ne "$expectedFileTypeCount" ]
then
    echo "Error downloading some GTFS.  One of the files is not a Zip file."
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some GTFS.  One of the files is not a Zip file." | mail -s "$serverName Build Error" $emailDistributionList
    fi
    exit 0
fi

# TEST 3: If that one file time is anything other than Zip.  Error!
fileType=$(file $newGtfsDataDir* | awk '{print $2}' | uniq)

echo "Downloaded the following file types"
echo $fileType
if [ "$fileType" != "Zip" ]
then
    echo "Error downloading some GTFS.  The GTFS is not a Zip file."
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some GTFS.  The GTFS is not Zip file." | mail -s "$serverName Build Error" $emailDistributionList
    fi
    exit 0
fi

# TEST 4: Check to see  if the new GTFS is different than the current GTFS
diffResult=$(diff $newGtfsDataDir $currentGtfsDataDir)
if [ ! "$diffResult" ]; then #this is the mac stat. Redhat might want a different format
    echo "The GTFS has not been updated. No need to rebuild."
    if [ "$verboseEmail" -eq "1" ] ; then
        echo "No new GTFS to Download. No action needed at this time. Stop this email by setting verboseEmail=0" | mail -s "$serverName No New GTFS" $emailDistributionList
    fi
    exit 0
fi

#Delete everything in the build folder
rm -rf $buildDataDir*

echo "Copying new gtfs to current GTFS folder"
cp $newGtfsDataDir* $buildDataDir

############################################################
## Download OSM Map (this only runs if we have new GTFS)
############################################################
echo "Reading CSV of OSM locations"
##Go through the osmExcelFile and remove the names column.
while IFS="," read Name URL
do
    echo $URL >> $osmTempFile
done < $osmExcelFile
wget -i $osmTempFile -P $newOsmDataDir

#Count the files in the directory to confirm all the OSM Maps downloaded
osmCount=$(ls $newOsmDataDir | wc -l)
expectedOsmCount=$(wc -l $osmExcelFile | awk '{print $1}')

# TEST 1: If expected number of OSM files is different than what was downloaded.  Error!
if [ "$osmCount" -ne "$expectedOsmCount" ] ; then
    echo "Error downloading some OSM"
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some OSM" | mail -s "$serverName Build Error" $emailDistributionList
    fi
    #TODO: Improve error message to be more helpful
    exit 0
fi

# TEST 2: If more than one file type was downloaded.  Error!
fileTypeCount=$(file $newOsmDataDir* | awk '{print $2}' | sort | uniq | wc -l)
expectedFileTypeCount=1
echo "Downloaded the following number of OSM file types (should always be 1)"
echo $fileTypeCount
if [ "$fileTypeCount" -ne "$expectedFileTypeCount" ]
then
    echo "Error downloading some OSM files.  One of the files is not a data file."
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some OSM files.  One of the files is not a data file." | mail -s "$serverName Build Error" $emailDistributionList
    fi
    exit 0
fi

# TEST 3: If that one file is anything other than Data.  Error!
fileType=$(file $newOsmDataDir* | awk '{print $2}' | uniq)
echo "Downloaded the following file types"
echo $fileType
if [ "$fileType" != "data" ]
then
    echo "Error downloading some OSM file.  The OSM is not a data file."
     if [ "$sendEmail" -eq "1" ] ; then
        echo "Error downloading some OSM file.  The OSM is not data file." | mail -s "$serverName Build Error" $emailDistributionList
    fi
    exit 0
fi

############################################################
## Build & Test the Graph
############################################################
echo "Building the new Graph.obj"
$invokeJavaCommand $otpJarDirectory$otpJar "--build" $buildDataDir

# Get the graph size
graphSize=$(ls -l $buildDataDir$graphFileName | awk '{print $5}')
#If the graph is small, then it's not fully built.  This thing failed.
minSize=10
if [ $graphSize -lt $minSize ]; then
    echo "Failed Building Graph"
    if [ "$sendEmail" -eq "1" ] ; then
        echo "Graph Building Failed" | mail -s "$serverName Build Error" $emailDistributionList
    fi
    exit 0
fi

############################################################
## SUCCESS! Clean-up, Upload Graph, and Restart OTP
############################################################
# Move the new GTFS to the current GTFS folder
rm -rf $currentGtfsDataDir*
cp $newGtfsDataDir* $currentGtfsDataDir

# Move the new OSM to the current OSM folder
rm -rf $currentOsmDataDir*
cp $newOsmDataDir* $currentOsmDataDir

# If there is Graph currently in production, move it to Graph.obj.old
if [ -f $otpGraphDir$graphFileName ] ; then
  cp $otpGraphDir$graphFileName $otpGraphDir$graphFileName.old
fi

#Move the new Graph to the production location
cp $buildDataDir$graphFileName $otpGraphDir$graphFileName

#Check to see  if the new Graph was successfully moved
diffResult=$(diff $buildDataDir$graphFileName $otpGraphDir$graphFileName)
if [ "$diffResult" ]; then
  echo "The Graph.obj has not been moved into production."
    if [ "$sendEmail" -eq "1" ] ; then
      echo "Graph.obj built, but Graph.obj couldn't be moved to the production location." | mail -s "$serverName Build Error" $emailDistributionList
    fi
  exit 0
fi

#TODO: Have an option to Restart OTP Automatically. There will be two hew variables 1) restartAutomatically 2) commandToRestart.  If #1 is true, execture #2
echo "Success! Restart the server to start using the new Graph.obj"
if [ "$sendEmail" -eq "1" ] ; then
  echo "A new graph was successfully built. If you have your server set to autoReload, then you are finished.  Otherwise, you will need to restart OTP for this new graph to take effect." | mail -s "$serverName Build Success" $emailDistributionList
fi
